### ISSUE TITLE
Recursive example incomplete?

### ISSUE THREAD

**Issue by phorward** [chc4/lineiform#1]
Hey! Shouldn't your README.md example for the recursive evaluation state
```rust
fn eval(ast: Ast) -> usize {
    match ast {
        Literal(l) => l,
        Add(left, right) => eval(left) + eval(right),  // <-- recursive call to eval missing!
    }
}

let val = eval(Add(Literal(1), Literal(2)));
val // 3
```
?

**Comment by chc4** [comment]
Woops, you're right - I copy pasted that part from a draft with a friend, where I manually corrected it in the actual conversation but not in my draft txt file. Nice catch!
